apiVersion: v1
kind: ConfigMap
metadata:
  name: model-save-map
data:
  S3_BUCKET: s3://wandb-finbert/
  MOUNT_PATH: /shared-efs

---
apiVersion: v1
kind: Pod
metadata:
  name: model-save-pod
spec:
  containers:
  - name: model-save-pod
    image: 999701187340.dkr.ecr.us-west-2.amazonaws.com/s3-efs
    envFrom:
    - configMapRef:
        name: model-save-map
    command: ["/bin/bash"]
    args: ["-c", "/model-save.sh"]
    volumeMounts:
    - name: efs-pvc
      mountPath: /shared-efs
  volumes:
  - name: efs-pvc
    persistentVolumeClaim:
      claimName: efs-claim
  restartPolicy: Never
